"""initial: players and mods

Revision ID: 6c7c3a4eb1f5
Revises: 
Create Date: 2026-09-25 03:11:23.498366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7c3a4eb1f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mod_type', sa.Enum('required', 'optional', name='modtype'), nullable=False),
    sa.Column('loader', sa.String(length=32), nullable=False),
    sa.Column('mc_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('access_token', sa.String(length=32), nullable=True),
    sa.Column('server_id', sa.String(length=41), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_index(op.f('ix_players_uuid'), 'players', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_uuid'), table_name='players')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_table('players')
    op.drop_table('mods')
    # ### end Alembic commands ###
