"""add server profile

Revision ID: 7068bd742a2f
Revises: ee5050a6b153
Create Date: 2026-09-27 15:30:31.484267

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7068bd742a2f'
down_revision: Union[str, None] = 'ee5050a6b153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mc_version', sa.String(length=32), nullable=False),
    sa.Column('loader', sa.String(length=32), nullable=False),
    sa.Column('loader_version', sa.String(length=64), nullable=True),
    sa.Column('server_address', sa.String(length=255), nullable=False),
    sa.Column('server_port', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Сидим строку профилем, который раньше был хардкодом в
    # client/ui_bridge/config.py::PROFILE — иначе после апгрейда бэкенд
    # останется совсем без профиля и /launcher/profile будет отдавать 404.
    server_profile = sa.table(
        'server_profile',
        sa.column('id', sa.Integer),
        sa.column('mc_version', sa.String),
        sa.column('loader', sa.String),
        sa.column('loader_version', sa.String),
        sa.column('server_address', sa.String),
        sa.column('server_port', sa.Integer),
        sa.column('updated_at', sa.DateTime),
    )
    op.bulk_insert(server_profile, [{
        'id': 1,
        'mc_version': '1.20.1',
        'loader': 'forge',
        'loader_version': '47.4.13',
        'server_address': '127.0.0.1',
        'server_port': 25565,
        'updated_at': datetime.now(timezone.utc),
    }])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_profile')
    # ### end Alembic commands ###
