"""add skin/cape hash to players

Revision ID: ee5050a6b153
Revises: 6c7c3a4eb1f5
Create Date: 2026-09-25 04:42:33.858162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5050a6b153'
down_revision: Union[str, None] = '6c7c3a4eb1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('skin_hash', sa.String(length=32), nullable=True))
    op.add_column('players', sa.Column('cape_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'cape_hash')
    op.drop_column('players', 'skin_hash')
    # ### end Alembic commands ###
